### ISSUE TITLE
[home page] Rethink Features Section Design, maybe add icons

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo.io#1]
current
![screencapture-localhost-1313-1489927091439](https://cloud.githubusercontent.com/assets/115347/24080963/bfc4a570-0c7f-11e7-85ac-c7321ed4a858.png)

Proposed (as an idea), from github.com (signed out)
<img width="1073" alt="screen shot 2017-03-19 at 8 41 18 am" src="https://cloud.githubusercontent.com/assets/115347/24080975/e8849b3c-0c7f-11e7-976d-99d94082cb5f.png">

**Comment by rdwatters** [comment]
Very cool. I'm excited to see what Forestry comes up with!

**Comment by budparr** [comment]
I've done a bit of work here. I got the icons from the Noun project (thanks @scottgallant for the suggestion). I don't *love* the icons, but it does help focus the text and still meets the original goal of flowing the features down the page.

TODO (in order of priority):

- [ ] **Refine the structure**. I just put this up quick-like, but it's lacking balance right now.

- [ ] With SVG, it's possible to **add some color to the images**. I just did a quick example for the shortcode image. This should be a very light touch. If anyone wants to take a crack at it, the images are here: https://github.com/budparr/gohugo.io/tree/master/themes/gohugo/static/images

- [ ] **Copy changes** Getting close on this. Some changes are suggested in #12  

- [ ] **Review the icons** I think the one I chose for "Shortcodes" is good, as well as "Built-in Templates," but def. open on the other ones.

**Comment by budparr** [comment]
Here's where we currently are. Cleaner, for sure, but feels "workmanlike" to me. I like having that much copy, because we have a technical audience. The icons are closer in size now (as well as the stroke-weights), but I think their varying level of detail in them still makes them seem off-balance to me. And the line-length on the multi-lingual box.


<img width="1440" alt="screen shot 2017-03-22 at 11 47 21 pm" src="https://cloud.githubusercontent.com/assets/115347/24231256/eab06530-0f59-11e7-88a6-57e689e94c16.png">


I also gave the heading some color. May not have enough contrast, so I may revert, but it does tie in some of the colors and gives the section some life.
<img width="1424" alt="screen shot 2017-03-22 at 11 52 48 pm" src="https://cloud.githubusercontent.com/assets/115347/24231494/5a8bad1e-0f5b-11e7-9dd0-5b3705997261.png">

**Comment by scottgallant** [comment]
@budparr looking great! I agree that the copy should stay for the technical audience; a challenge for sure.  There are a lot of things going on here, so I hacked on your designs for a few mins to try to simplify the layout. Thoughts? 

![screen shot 2017-03-23 at 10 41 44 am](https://cloud.githubusercontent.com/assets/776019/24250538/fa148cd4-0fb5-11e7-9b83-fd735e9d743a.png)

**Comment by budparr** [comment]
noting here what we came up with.
<img width="1440" alt="screen shot 2017-03-23 at 5 39 33 pm" src="https://cloud.githubusercontent.com/assets/115347/24271484/b53f44ac-0fef-11e7-945e-92f9cab3ad3f.png">

**Comment by budparr** [comment]
And, thanks to @digitalcraftsman for pushing on this too!

**Comment by digitalcraftsman** [comment]
@budparr I like the final outcome of your work! Especially the matching icons :+1:

**Comment by rdwatters** [comment]
This is awesome! :smile: 

Here's all I got:

1. Might be better to break into single column a bit sooner for features, Twitter cards, and the terminal. It also gets slightly off center on smaller screens.
2. Perhaps a solid dark bg on the footer in light of the green in the logo? 
3. Buttons on mobile footer nav are not vertically aligned, although I'm not sure if this is intentional or not.
