### ISSUE TITLE
Copy Changes to Homepage

### ISSUE THREAD

**Issue by rdwatters** [budparr/gohugo.io#12]
This just keeps looking better and better! 

**Current**

> Hugo is the fastest tool of its kind. At less than 1 ms per page, the average site builds in less than a second.

**Suggested**

Do we need the math? 

> Hugo is the fastest tool of its kind. The average site builds in less than a second.

**Current**

> Shortcodes are Markdown's hidden super power. Hugo has them, and you can even write your own.

**Suggested**
Something about this feels clumsy. I think it's the "Hugo has them" and the "even." Perhaps combine them into a single, non-comma-delimited clause? Note that "superpower" is one word, and we should be consistent in capitalization of *Markdown* or *markdown*. (I need to change this in the docs concept too.)

> Shortcodes are Markdown's hidden superpower. Use Hugo's built-in shortcodes or write your own. 

(I'm not attached to "built-in," but I think you get the idea.)

**Current**

> Hugo loves Markdown because of its simple content format, but there are times when markdown falls short. We think this contradicts the beautiful simplicity of markdown’s syntax. Hugo created shortcodes to circumvent these limitations.

**Suggested**

I think you copied and pasted these sentences from the introductory paragraph [here](https://hugodocs.info/content-management/shortcodes/). The problem is the omission of the following sentence: "Often, content authors are forced to add raw HTML (e.g., video <iframes>) to markdown content." Right now, it doesn't really make sense unless you're saying "Markdown's shortcomings contradict its beautiful simplicity." I *guess* this makes sense? How about the following instead?

> Markdown shows the limits of its beautiful simplicity when authors are forced to add raw HTML to content. Hugo created shortcodes to circumvent these limitations.

**Current**

> Polyglot baked in.

**Suggested**

I'm sticking to the idea that "polyglot" is not internationally recognizable, but this is the weakest point so far in this list of changes. :smile: 

**Current**

> Check out the themes showcase.

**Suggested**

Frankly, I just hate the word "showcase."

> Check out Hugo themes.

**Current**

> Hugo works on OS X, Windows, Linux, FreeBSD, and others. Host on any server, even your favorite CDN.

**Suggested**

> Hugo works on macOS, Windows, Linux, FreeBSD, and others. Host on any server or your favorite CDN.

**Current**

> Hugo's Go-based templating provides just the right amount of logic to build anything from the simple to complex.

**Suggested**

You need the definite article before both elements in the range for parallelism. I'd also remove "Go-based." Do we want to emphasize Amber and Ace? I like the way you tied it to the popular Jade and Pug syntaxes. I only ask because I combined them in a way that might deemphasize their sexiness in the docs concept.

> Hugo's templating provides just the right amount of logic to build anything from the simple to the complex. If you prefer Jade- or Pug-like syntax, you can also use Amber, Ace, or any combination of the three.

**Current**

> See the getting started guide. 

**Suggested**

Do you mean the "Quick Start" or just "See the Getting Started guide?" 

**Aside:** When you're at that point, would you mind linking to the docs concept for continuity? I know you're still iterating, so NBD.

**Comment by budparr** [comment]
Thanks, @rdwatters. Come up with a better word than Polyglot, my friend, and we'll replace it, but I think I've already justified its existence. 

I think "do we need the math" sounds condescending.

> when authors are forced to add raw HTML to content.

I don't think we gain anything by trash-talking Markdown too much.

Jade and Pug are the same thing. Jade was renamed to Pug, but Pug seems to be referred to as Jade/Pug for the time being. 

Otherwise, looks good.

**Comment by budparr** [comment]
Also, this one. " At less than 1 ms per page," Specificity is good with a technical audience, methinks. Arguably, part of our audience is someone coming from the Jekyll's of the world and that build-time is the single-most important thing they're here for, because they're tired of waiting. I think quoting the per page speed is important because average could mean anything.

**Comment by rdwatters** [comment]
> I think "do we need the math" sounds condescending.

Sorry about that. Didn't mean to seem like I was talking down to you, brother. Also, I like math, haha. You make a good point about the coming from Jekyll and per-page speed I didn't think about. 

And "doi" on the Pug/Jade syntax. I should have thought that one through. 

> average could mean anything

Very true. I retract my suggestion. 

As for "polyglot," the issue is probably that I just need to let it go.

**Comment by rdwatters** [comment]
> I don't think we gain anything by trash-talking Markdown too much.

True. Hmm. This could be rephrased more delicately for sure. Do you think "falls short" knocks it too much as well? (I'm asking in the context of that page as in the docs as well.) Maybe go more the route of something like "Sometimes you want to easily add more complexity than is afforded by markdown's beautifully simply syntax?" Then we are tipping our hat to markdown without making it seem like a deficiency. This is spitballing.

**Comment by budparr** [comment]
I didn't mean condescending to me, I meant to our audience.

**Comment by budparr** [comment]
Some people say "do the math" in a "you clearly don't get it, do the math and you'll see" way.

**Comment by rdwatters** [comment]
Ohhhhh, now I get it. That was just a question to you about the actual math part. As in, thinking of 1ms within a 1-second context. That's why it was a question outside the blockquote. Now I get it. Plus, I figured a negative interpretation would be justified since my St Patty's rant :wink:

**Comment by budparr** [comment]
Note that we may be able to get some graphics https://github.com/budparr/gohugo.io/issues/1 so, the copy here will need to adjust to that.

**Comment by rdwatters** [comment]
I just want to reiterate how much I love this line, btw:

> Flexibility rules. Hugo is a content strategist's dream.

Outside of your work, especially the Jekyll Conf video (awesome,btw), I feel the content strategy piece is really underrepresented when people talk of SSG benefits.

**Comment by budparr** [comment]
I agree. There's a little bit of a lie there. Hugo's one-to-one mapping with content folders to URLs (even with the permalink setting) is a bit constraining, but otherwise it is indeed a dream.

**Comment by budparr** [comment]
I should say, though, that aside from that content, that setup is very nice and predictable for most use-cases.

**Comment by rdwatters** [comment]
> I should say, though, that besides that, the way content works is very nice and predictable for most use-cases.

Agreed. I just like that it's an SSG that refers to my line of work. It is an entirely solipsistic assessment :smile:

**Comment by budparr** [comment]
I captured the changes here, with some adjustments for space, or things we talked about. Closing this issue and we can open another, if needed. Thanks!
