### ISSUE TITLE
Improve the command line on the getting started block to bring home that it's easy across platforms

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo.io#2]
Current:
<img width="369" alt="screen shot 2017-03-19 at 5 09 54 pm" src="https://cloud.githubusercontent.com/assets/115347/24084766/fe51826c-0cc6-11e7-84ec-21810cfe45de.png">

take into account this suggestion:
> Below you added a few commands to install Hugo via brew (on OS X). What do you think about the addition of a panel with tabs, where the user can choose the source manually? Currently, third-parties maintain packages for nearly every platform:

> OS X
> - brew
> - Windows
> - chocolatey
> Linux
> - Arch / Manjaro
> - Debian / Ubuntu
> - Fedora

I think that may be too much for the home page, and the job of the docs, but I think we can find something that gets across that it's not hard across a variety of platforms.

**Comment by budparr** [comment]
if we had to only show one command (or, for sake of argument, assuming that a reader is going to skim over anything fancy we do, so should lead with our best), what would that command be?

This looks like it would be difficult if I were coming from Wordpress:

```
 export GOPATH=$HOME/go
$ go get -v github.com/spf13/hugo
```

@rdwatters  @digitalcraftsman

**Comment by rdwatters** [comment]
> This looks like it would be difficult if I were coming from Wordpress:

W/r/t a command line or the Go-specific bits?

Just to provide some context: 

I was going to write a little browser sniff that would show the command according to the user's OS (i.e. to obviate the tabs).

I checked the GA for some insight, but benchmark data isn't enabled. We might be able to get this elsewhere w/r/t downloads, but this might not be very elucidating. 

I like `brew update && brew install hugo`, but that undermines the "every platform" bit and doesn't help if users are just uncomfortable with the command line.

**Comment by budparr** [comment]
I did this. It's not perfect. I just the we ought to have the simplest way there for now. Fancy stuff can follow, whenever...
<img width="518" alt="screen shot 2017-03-23 at 9 26 02 pm" src="https://cloud.githubusercontent.com/assets/115347/24276795/85f54f28-100f-11e7-99b6-8d13da5c6dc7.png">
