### ISSUE TITLE
Apply redesign to theme site

### ISSUE THREAD

**Issue by digitalcraftsman** [budparr/gohugo.io#20]
The redesigned homepage and docs are already on a good way. Layout and design changes should also be applied to the [themes site](http://themes.gohugo.io/).

**Comment by rdwatters** [comment]
@digitalcraftsman @budparr I just went ahead and made the couple small changes that @budparr made when he sent us that screenshot in the browser but figured I was holding off until Bud made some strides with the components and other pieces he was talking about. That said, if it's easier for me to look at the new News site and emulate it accordingly and then we reconvene on it later, I'm happy to do so. I know you've done a ton of work on this over the past couple weeks Bud.
