### ISSUE TITLE
Shortcodes for the new docs and news/blog

### ISSUE THREAD

**Issue by rdwatters** [budparr/gohugo.io#21]
@digitalcraftsman @budparr 

In the interest of creating editorial guidelines and improving submission guidelines, I want to know whether you two see new content for news/blog requiring some of the [shortcodes I created for the docs](https://github.com/rdwatters/hugo-docs-concept/tree/master/layouts/shortcodes). The first that springs to mind is the code block shortcode because it is both copyable and downloadable, but there *could* be utility for some of the others (e.g., if the blog includes tutorials). 

This is only a question of functionality (html, js) since I'll be leaving it up to Bud to style these however he sees fit. 

This also speaks to the larger question of whether both sites should be using a singular theme instead, which I appreciate is difficult for multiple reasons, not the least of which is that Bud and I are using different build tools, etc. We can address this here or in a different thread, since it's been mentioned before. I appreciate your feedback.

**Comment by budparr** [comment]
I would *like* to use the same theme. What are you using the build tools for that couldn't be integrated into another theme?

**Comment by rdwatters** [comment]
> What are you using the build tools for that couldn't be integrated into another theme?

Well, maybe it's not the build tools, but I'm pretty perf-obsessed. For example, I use CRP across the board on the docs site, embed highly optimized versions of the SVGs, etc, all of which could definitely be part of a new theme, but I feel like that's going to be awfully burdensome for you. I also use the [SASS guidelines](https://sass-guidelin.es/) for architecture, zero in the way of frameworks, and am using gulp with uglify and other bits etc that I just don't want to add extra setup time to what you're currently using with webpack (which I haven't used but need to learn anyways). The site only has one asynchronous, deferred script tag for everything outside of the vendor deps (e.g, GA, Algolia, etc). I'd like to keep it as fast as it currently is while not making your workload super irritating:)
