### ISSUE TITLE
Toward a unified search model

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo.io#22]
Carrying on a discussion about [search](https://github.com/budparr/gohugo.io/issues/4#issuecomment-289222156), I think this needs to be considered a bit.

**Points for Consideration**

- Docs, obviously need search, and have that built already.

- News may or may not need search (perhaps in time), but if there's a search box on the site it should search the docs as well. It may be confusing/noisy to do search on the news site and have it search the docs too. So perhaps it needs its own search, but then again, that could in and of itself be confusing if someone just hits the site and wants to get something on the docs.

- If one search for docs and news, is that technically a capability of Algolioa, or outside of the scope of the free program?

- Begs the question of an built, open-source solution as opposed to a commercial solution. Thoughts?

TODO:
- [ ] Add search to 404 page, for at least docs (suggested by @digitalcraftsman)

**Comment by rdwatters** [comment]
> If one search for docs and news, is that technically a capability of Algolioa, or outside of the scope of the free program?

Can you expand on that? Are you talking about facets? As far as the free program, I'll check, but my guess is that we are still okay...

> It may be confusing/noisy to do search on the news site and have it search the docs too.

I see this as a nonissue until we have enough posts, news items, and releases to cause any noise. Right now, the most noise comes from a) the showcase and b) the tags pages. I'd like to move *a* out of the docs and news sites entirely and I *believe* that *b* can be dis-included: https://github.com/algolia/docsearch-configs/blob/master/configs/hugodocsconcept.json

The way I have Algolia configured at the moment, it shows the section > page > and then page section (i.e. heading). If we keep things as hugo.io/news, users should be able to intuit these respective sections pretty quickly.

> Begs the question of an built, open-source solution as opposed to a commercial solution. 

I'd stick with Algolia docsearch for the following reasons:

1. It's not entirely OS, but it's free :smile:
2. The analytics pane is really informative: you can set trends, etc. This makes it easier to find out how our users are actually using the site.
3. As demonstrated [here](http://cordova.apache.org/docs/en/latest/), version-based search is OOB.

The only shortcoming for me with the current search is that search terms don't show up in GA, but this is being worked on by Algolia, or we can roll our own with their plugin. This probably requires a separate conversation...

**Comment by budparr** [comment]
> technically a capability of Algolioa

to have the content of two sites in one search console. I doubt it.

**Comment by rdwatters** [comment]
> to have the content of two sites in one search console. I doubt it.

...

> If we keep things as hugo.io/news, users should be able to intuit these respective sections pretty quickly.

Why wouldn't it be able to index both and show results for /news as a site section? 

This also depends on the content we expect in the News section. For example, if a contributor writes an article about using a Hugo menu on a specific project, wouldn't we want it to pull up with the docs? 

I already reached out to see if indexing not-entirely-docs-content is a violation of Algolia's generosity.

What other solutions are you thinking of? I know there was some chat about [Bleve](https://discuss.gohugo.io/t/how-are-you-implementing-site-search/986/26?u=rdwatters) a while back in the forums, but I have no direct experience. At least it's Golang based, which is cool.

If you want to go client side, we could dogfood custom outputs too. I've built a couple Hugo sites with lunr.js, and I know we have both used Tipue.

**Comment by budparr** [comment]
> Why wouldn't it be able to index both and show results for /news as a site section?

Okay. Guess I'm wrong on this then. Glad they can do that.

**Comment by rdwatters** [comment]
> Okay. Guess I'm wrong on this then.

Not necessarily. To your point, if these end up being subdomains...

There's also the bigger question of whether one search should index both. I'm open to suggestions if you know a better OS solution too or dogfood custom outputs as I mentioned above.

**Comment by budparr** [comment]
> … if these end up being subdomains...

I was operating on that [assumption](https://github.com/rdwatters/hugo-docs-concept/issues/40#issuecomment-287565035). Not sure how they could be otherwise, really.

> There's also the bigger question of whether one search should index bot

We might be going in circles here. _should_ was the basis of my initial query.

**Comment by rdwatters** [comment]
> Not sure how they could be otherwise, really.

[Proxies](https://www.netlify.com/docs/redirects/#proxying). 

> Begs the question of an built, open-source solution as opposed to a commercial solution. Thoughts?

All the *should*s aside...

Third time now: do you have any other solutions in mind? I'm not super familiar with anything other than what I mentioned above (Bleve, Lunr, Tipue) and will gladly research or do the reaching out if needed and still wonder whether you think this could also be a good dogfooding opportunity for custom outputs.

**Comment by budparr** [comment]
Sorry, Ryan I must not be communicating very well here. The original question was about whether or not the home/news site should have search available to it, and if so, what that would look like. You seem to have a good handle on the technical aspects of these questions, so I will leave it to you and the others.

I posed the question about Algolia, and I shouldn't have, because it has appeared to have muddled the original question. You answered it adequately, and I've not challenged your assertion, and don't care to dwell on it with the limited time I have for this project. This conversation has gotten too meta for, and slightly offensive, so I'm going to close this issue for now.

**Comment by rdwatters** [comment]
This is my fault for harping on questions 3 & 4 rather than the precursors of 1 &2, @budparr. My apologies for not making the connection 🙇
