### ISSUE TITLE
Toward a post design

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo.io#3]
Notes:
Goal here was to put a lot of emphasis on the description and author bio. We're pulling in the author bio from the Github API (assumption that any contributor to this site would have a Github account). This is meant to be an example of using a Hugo feature.

<img width="1440" alt="screen shot 2017-03-20 at 8 13 47 am" src="https://cloud.githubusercontent.com/assets/115347/24099380/4217f408-0d45-11e7-8504-78803f07cd0a.png">

---

with notes

<img width="1440" alt="screen shot 2017-03-20 at 8 13 47 am-withnotes" src="https://cloud.githubusercontent.com/assets/115347/24099431/95d9614e-0d45-11e7-8037-5e3825a37672.png">

**Comment by rdwatters** [comment]
Ahh, Bud! This looks freakin' AWESOME! 

What do you think about implementing some of these design changes on the docs site so we can present it to the team? Or I can try my hand at changing them as well. I know you forked the docs site, so LMK. I'll push my most recent changes now...

**Comment by rdwatters** [comment]
Also, is "tips" where you see Community-developed blog posts about how to tackle specific Hugo projects living?

**Comment by budparr** [comment]
I just threw tips out there. I think we can talk about "editorial strategy" at some point, but I do think this (non-commitally named) named news section could be a place that things that aren't quite permanent enough for the docs.

**Comment by rdwatters** [comment]
>  I think we can talk about "editorial strategy" at some point

I think our thoughts are already in alignment here. The docs concept required a few considerable purges, but I'd actually like to purge even more...

**Comment by digitalcraftsman** [comment]
I totally agree with @budparr: the design looks absolutely awesome. Just one small critique: the main menu in the top right looks a bit squished and should be aligned with the tags.

Regarding the author information: there's a WIP progress that will allow Hugo to have support for authors out of the box. It's unlikely to be included in the upcoming release. Shortly after that I'll have time to get hands on it to finish it. Instead of pulling the infos via the GitHub API we could add a simple author profile which work similar to data files.

**Comment by budparr** [comment]
> Instead of pulling the infos via the GitHub API we could add a simple author profile which work similar to data files.

That's fine by me. Aside from giving prominent credit to authors, my intent was to use a Hugo feature, so both qualify, and using the author feature gives us a bit more control of the data, though require users to input/update data in an additional place. Tradeoff, but like I said, I think either is good.

> main menu in the top right looks a bit squished and should be aligned with the tags.

Agree. This is entirely a [wip]

**Comment by digitalcraftsman** [comment]
What do you think about the addition of a few sharing options?

**Comment by budparr** [comment]
I tend to do that sort of thing last.
