### ISSUE TITLE
Toward a light content model

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo.io#4]
cc @rdwatters

Goal with the content here is to keep it simple so anyone can step into the site with little thought.

Aside from home page content, which is ad hoc, there's one content section on this site: "News"

News posts separated, potentially, but categories, e.g. "Releases," "Tips," "Showcase"

Archetype:
```
---
author: github-username
categories: ["Releases"]
date: 2016-10-07T13:54:06-04:00
description: "Hugo now supports multilingual sites with the most simple and elegant experience."
title: "October Release: Hugo is going global"
---
```

**Comment by budparr** [comment]
Noting here that I'm aware of a new author model coming down the pike in Hugo. I'm using the Github API to automatically pull in bio for the author as well as a link to their profile, but that's not set in stone, and may be re-considered.

**Comment by rdwatters** [comment]
> Noting here that I'm aware of a new author model coming down the pike in Hugo.

Yup. Just for easy ref: https://github.com/spf13/hugo/pull/1850

> Aside from home page content, which is ad hoc, there's one content section on this site: "News"

Is "tips" just placeholder? I like the idea of using taxonomies (i.e., "categories") as long as it doesn't get too crazy.

Question re: search: 

Right now, the docs concept and the free Algolia docs search are working really, really well together. What are you thinking in terms of the search experience? Note: I'm using both categories and tags on the docs concept, but the categories are single-value across the board and reflect verbatim the site section. I couldn't think of how to use this additional taxonomy, so currently taxonomy-categories pages are not being built, and I figured the 1-to-1 was an easy future proofing piece for moving the content files in the future.

My assumption is that users will want to be able to search across both "properties"...

Thoughts?

**Comment by rdwatters** [comment]
> Goal with the content here is to keep it simple so anyone can step into the site with little thought.

Not to put the cart before the horse, but maybe we can add a "contrib to the blog/news/whatever" page in the [current "contribute" menu?](https://hugodocs.info/contribute/).

**Comment by budparr** [comment]
Yes, "Tips" is a placeholder, in fact it's a placeholder for the placeholder. When I design something like that I put in edge-case scenarios, and currently it's breaking :)

Search is a bit tricky, if you mean search on this site that would lead to the docs site. But I'm open to ideas. 

> an add a "contrib to the blog/news

Totally.

**Comment by rdwatters** [comment]
> Search is a bit tricky, if you mean search on this site that would lead to the docs site. But I'm open to ideas.

If we keep the news and docs as directories rather than subdomains&mdash;I'd vote for this for additional reasons as well&mdash;we don't have any additional work in terms of setting up search. It's a daily crawl from Algolia, and we have access to the config on GH (I've already made a PR in the past) and you'll see it's pretty damn powerful on the docs concept site now. We just have to continue to keep up the semantic improvements and consistent heading structure.
