### ISSUE TITLE
Homepage design issues/improvments

### ISSUE THREAD

**Issue by budparr** [budparr/gohugo.io#8]
Placeholder

**Comment by budparr** [comment]
> ...I think the main links "Blog Docs Community Themes" is oddly placed. When I first see that I think that's what Hugo's features are

**Comment by budparr** [comment]
> I may suggest a reorder of his actually
> I'd keep the top as it is (with minor adjustments) and the news where it is.
> I'd then put the featured users
> then the themes and templating

**Comment by digitalcraftsman** [comment]
Hey @budparr,

I did it again and compiled a list of possible adjustments to the design :smile: 

- the octocat in the top right seems a bit redundant because the GitHub repo is already linked in the main menu right next to GitHub's mascot
- the font size of the menu links is rather small
- what do you think about centering the logo and menu like content below in the hero section?
- the quickstart button is the entry point for new users. we should make this a bit larger
- I can see that you try to use all the colors from the Hugo logo. But the green background in the footer decreased the contrast, especially for the blue links in "By spf13 and friends"
- when zooming out the whole website looks streched. Does the layout behave the same on (ultra) widescreen monitors? At the time of writing this I'm not able to test it myself. If so we might limit the max-width of the layout.

**Comment by budparr** [comment]
Hey, @digitalcraftsman Thanks for the input. Designing is partly about creating a hierarchy and telling people what's important,  The audience of those who use that page as a jumping off place to the rest of the Hugo ecosystem are repeat users and more engaged than what I see as the highest level audience, who we are telling to read down the page. If we made everything big then there'd be no hierarchy. Redundancy isn't always bad either; the Octocat is not so much a link, as a message.

I agree with you about the footer. I felt it was wrong almost as soon as I put it up. :) Sometimes, though, I just let things stay while I'm in a process of iteration like this, just to think through how it might be different, etc. I'm not normally iterating with so many critical eyeballs, so I'll keep in mind to keep my toying to myself. 

The zooming thing isn't something I've thought too much about, frankly (we always obsess over mobile, at the expense of ultra-wide). I haven't had the privilege of seeing the stats (guess I should ask to see them!). You could say on an ultra wide the layout fails, though only to a degree. There are some assumptions we have to make (like would a user expect a site/most sites to be workable at a really wide width where the resolution doesn't make up for the size?) and design accordingly. But thanks for bringing it up.

**Comment by digitalcraftsman** [comment]
> I'm not normally iterating with so many critical eyeballs, so I'll keep in mind to keep my toying to myself.

I hope I'm not to harsh with my comments about your work. You've definitely more experience regarding design decisions and has to be kept in to account. The audience of Hugo users is wide ranging from software devs to cusual users who want to try out this "static thing". 

Feel free to experiment with your design. As with software it can take some time and thinking until you think you did it right. The design is a WIP. From a designers perspective: are the small design changes  a help for your design process, i.e. I have to sleep a night about this, or is it rather meant as an A-B test were you compare to versions and see how users react?

> Designing is partly about creating a hierarchy and telling people what's important

I agree. New users need a hierarchy if they're trying Hugo for the first time. While rethinking about it makes sense that visitors might stay some time on the homepage to get a 30.000 foot view of what Hugo is about and which capabilities it has.

> I haven't had the privilege of seeing the stats (guess I should ask to see them!).

@rdwatters might be able to help here. He's using the stats of the visitors to place certain pieces of content more strategically. (Ulta) widescreen monitors aren't as common as smartphones to visit websites. I'm not saying that we've to treat this users specially but would just add a wrapper that limits the width of the content (like the `.container` class of Bootstrap) to prevent that some text appears on the very left of the screen and the corresponding picture on the very right.

**Comment by budparr** [comment]
> I hope I'm not to harsh with my comments about your work.

No, you're not. You have no way of knowing my thought process. If I push back on stuff, it's not because I think I'm always right, it's just that I've thought through it and had to make a decision. So some things I say hey, that's right. Others I just think about, and sometimes dismiss. It is, admittedly, harder to work under such scrutiny, but I hope I only bring professionalism and experience to the table, not ego. 

> From a designers perspective: are the small design changes a help for your design process, i.e. I have to sleep a night about this, or is it rather meant as an A-B test were you compare to versions and see how users react?

A little bit of both. But part of it is, that web design, in particular, is like designing a small sailboat, where everything has to fit just so. So sometimes, you make a set of decisions for one thing, and before you want to go and change other things, you sit on it a bit to make sure the first one is solid. Particularly, since I go back and forth between Sketch and code.

**Comment by digitalcraftsman** [comment]
> I hope I only bring professionalism and experience to the table, not ego.

There's no trace of your ego in your work.

**Comment by budparr** [comment]
I think I've covered these. Feel free to create a new issue.
